description = "The UML mofext for AMF"
website = "https://forge.ada-ru.org/matreshka"
name = "matreshka_amf_mofext"
version = "18.1.0"
origin = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_amf_mofext-18.1.tar.gz"
authors = ["Vadim Godunko"]
licenses = ["BSD 3-Clauses"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_amf_mofext.gpr"]
tags = ["uml", "meta", "diagram"]
origin-hashes = ["sha512:033eaa76b1519d81565e73f5393e351b8a460cfee4783eed7b4bdf68d59b1295bdbf3dcd4cfd545b5beb755522d230c563173f365203f86bd384e33c49d8c881"]

[[depends-on]]
matreshka_amf_uml = "any"
matreshka_league = "any"
