description = "The GNU Scientific Library (GSL)"
name = "libgsl"
licenses = []
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

[[external]]
kind = "system"
origin = ["libgsl-dev"]
