description = "Simple Components - A collection of support packages"
website = "http://www.dmitry-kazakov.de/ada/components.htm"
name = "simple_components"
version = "4.42.0"
notes = "Tasking=Single seems to be broken at persistent-single_file-text_io.adb"
origin = "http://www.dmitry-kazakov.de/ada/components_4_42.tgz"
authors = ["Dmitry A. Kazakov"]
licenses = ["GMGPL 2.0"]
maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]
origin-hashes = ["sha512:d428a64b7e457d616dd402ac75f8324e7564ed42e667c8efc909079638213426232ea6d856f1080b633d5bb90dda5567073b8e66cbb55462f27ea64ff7360107"]
project-files = ["components.gpr", "components-connections_server.gpr", "components-connections_server-elv_max_cube.gpr", "components-connections_server-http_server.gpr", "components-connections_server-http_server-sqlite_browser.gpr", "components-connections_server-modbus.gpr", "components-connections_server-mqtt.gpr", "components-connections_server-secure.gpr", "components-connections_server-smtp.gpr", "components-gnutls.gpr", "components-ntp.gpr", "components-odbc.gpr", "components-sqlite.gpr", "strings_edit.gpr", "tables.gpr"]

[[depends-on]]
libgnutls = "^3.5.8"
unixODBC = "^2.3"

[gpr-externals]
Atomic_Access = ["Pragma-atomic", "GCC-built-ins", "GCC-long-offsets"]
Development = ["Debug", "Release"]
Legacy = ["Ada95", "Ada2005", "Ada2012"]
Tasking = ["Multiple", "Single"]
Traced_Objects = ["Off", "On"]
[gpr-set-externals."case(os)".linux]
odbc = "unixODBC"

[gpr-set-externals."case(os)".windows]
odbc = "ODBC32"
[gpr-set-externals."case(word-size)".bits-32]
arch = "i686"

[gpr-set-externals."case(word-size)".bits-64]
arch = "x86_64"
