description = "The UML Testing Profile for AMF"
website = "https://forge.ada-ru.org/matreshka"
name = "matreshka_amf_utp"
version = "18.1.0"
origin = "https://github.com/reznikmm/matreshka-alire/archive/matreshka_amf_utp-18.1.tar.gz"
authors = ["Vadim Godunko"]
licenses = ["BSD 3-Clauses"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>", "Maxim Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["godunko", "reznikmm"]
project-files = ["build_matreshka_amf_utp.gpr"]
tags = ["uml", "meta", "diagram", "testing"]
origin-hashes = ["sha512:3111ac1e8fded184d2f64807c486667a35e43c843dbcdc33a11ecab1288dc6460f8bfa9ef71e9b052da726201b53e1e32ad102ca3537ffcf188f97bdc3a81333"]

[[depends-on]]
matreshka_amf_uml = "any"
matreshka_league = "any"
