##
## Mandatory properties follow, uncommented. Fill 'em all!
##

name = "my_crate_name"

## The release version stored in this manifest, following semantic versioning rules: https://semver.org
version = "0.1"

description = "One-liner describing the project (72 chars max)"

## See possible licenses at https://github.com/alire-project/alire/blob/master/doc/catalog-format-spec.rst#general-info
licenses = ["LGPL 3.0"] 

## Contact emails of the maintainers of this file
maintainers = ["your@email.com"]

## GitHub login of people allowed to modify this file
maintainers-logins = ["user1", "user2"]

##
## Optional properties follow. Uncomment and fill any that apply
##

## Long description, can be multi-line using """ """ as delimiters
# long-description = """
# A very very long Markup text can be given here.
#"""

## Executables built (must not include any relative path)
# executables = []

## Project files made available to clients (with relative path)
## If only a single project file named as the crate is provided
## at the root directory, then this property can be omitted.
# project-files = []

## Keywords for classification
# tags = []

## A website with further information
# website = "url"

## 
## ORIGIN: this is where your sources are found
##

[origin]
url = "https://URL_TO_ARCHIVE.tar.gz.or.zip"
hashes = ["sha512:hexadecimal-hash-goes-here"]

## Alternatively, a git/hg/svn repository and commit can be given.
## In that case, hashes cannot be provided:
# url = "git+https://URL/to/repo"
# commit = "3cb3d3f892fb73bbfd60296e177049fde92f3bb1"

## Dependencies needed by this release. Dependencies must be given
## as a TOML array of tables, each table containing a dependency.
# [[depends-on]]
# libfoo = "^1.0"
# ...
