description = "Knowingly unavailable dependency template"

long-description = "This is a placeholder for an unsupported crate. Please contact the maintainer if you want to take over packaging and maintenance of this crate."

maintainers = ["alejandro@mosteo.com"]
maintainers-logins = ["mosteo"]

licenses = []
tags = []

[[external]] 
# A external crate never found during dependency resolution.
kind = "hint"
hint = "This crate is unavailable through Alire. Please check upstream installation documentation."
