description = "GNAT Components Collection - Core packages"
name = "gnatcoll"
authors = ["AdaCore"]
licenses = ["GPL 3.0"]
maintainers = ["derodat@adacore.com"]
maintainers-logins = ["pmderodat"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["libgnatcoll16.1.0-dev", "libgnatcoll17-dev", "libgnatcoll18-dev"]
