description = "GNAT Components Collection - Core packages"
name = "gnatcoll"
authors = ["AdaCore"]
licenses = ["GPL 3.0"]
maintainers = ["derodat@adacore.com"]
maintainers-logins = ["pmderodat"]

[[external]]
kind = "system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["libgnatcoll16.1.0-dev", "libgnatcoll17-dev", "libgnatcoll18-dev"]

[gpr-externals]
BUILD = ["DEBUG", "PROD"]
GNATCOLL_ATOMICS = ["intrinsic", "mutex"]
GNATCOLL_OS = ["windows", "unix", "osx"]
LIBRARY_TYPE = ["relocatable", "static", "static-pic"]

[gpr-set-externals]
BUILD = "PROD"
LIBRARY_TYPE = "static-pic"
[gpr-set-externals."case(os)".linux]
GNATCOLL_OS = "unix"

[gpr-set-externals."case(os)".macos]
GNATCOLL_OS = "osx"

[gpr-set-externals."case(os)".windows]
GNATCOLL_OS = "windows"
